### PR TITLE
Cabal2 fix

### LINKED ISSUE #21: Build failure with Cabal 2.0
```
[4 of 4] Compiling Main             ( Setup.hs, Setup.o )

Setup.hs:29:34: error:
    Ambiguous occurrence ‘Version’
    It could refer to either ‘Distribution.Simple.Version’,
                             imported from ‘Distribution.Simple’ at Setup.hs:11:1-26
                             (and originally defined in ‘Distribution.Version’)
                          or ‘Data.Version.Version’,
                             imported from ‘Data.Version’ at Setup.hs:16:1-19
   |
29 | data Aux = Aux { guideVersion :: Version }
   |                                  ^^^^^^^
```

### PR DESCRIPTION
**Pull request by Kranioceros**
This fixes #21 by simply not using the Version datatype from Data.Version in Setup.hs. It also uses a different function for reading Package descriptions, since the old one is no longer available in Cabal 2.

This fix is dependent on the previous one I made for issue #22. I'm new to git, so please correct me if I made a mistake here.

### CODE REVIEW

**Comment by Daniel-Diaz** [comment]
This looks good, but since it includes changes from another PR, the other PR should be merged first.

**Comment by Daniel-Diaz** [comment]
For reference: https://github.com/Daniel-Diaz/hatex-guide/pull/23.

**Comment by Kranioceros** [comment]
Roger that!

**Comment by Daniel-Diaz** [comment]
It looks like the code from this PR is not updated with the newest CPP changes. You might want to merge those changes into this branch.

**Comment by Kranioceros** [comment]
Ok, I think it's ready to go now.

**Comment by Daniel-Diaz** [comment]
Awesome! Thank you!

**Pull request merged**
