### PR TITLE
Add Semigroup instance for Syntax datatype

### LINKED ISSUE #22: Build failure for Base >= 4.11
I tried to install hatex-guide with Stack (lts-12.9) but the build failed with the following error:

```
Text/LaTeX/Guide/Syntax.hs:77:10: error:
• No instance for (GHC.Base.Semigroup Syntax) arising from the superclasses of an instance declaration
• In the instance declaration for ‘Monoid Syntax’
     |
77 | instance Monoid Syntax where
     |          ^^^^^^^^^^^^^
```

This seems to happen because of the change in version 4.11 of base, in which Semigroup is now a superclass of Monoid. Two possible fixes come to mind:

- Write a Semigroup instance for Syntax
- Restrict the version of base in the project .cabal file. Currently, the restriction is too lax: base = 4.*

### PR DESCRIPTION
**Pull request by Kranioceros**
Fixes #22 by adding a Semigroup instance

### CODE REVIEW

**Comment by Daniel-Diaz** [comment]
Hey, thanks a lot for the PR!

There is only an issue with this approach, and is that it will break the build for older versions of base that do not export `Semigroup`. I think it's too soon to drop support for those versions of base that are still widely in use. This could be fixed using CPP.

**Comment by Kranioceros** [comment]
OK, I'm very new to this, so you'll have to bear with me if I start to create too many branches or make too many PRs. Having said that, I'll try to fix this.

**Comment by Daniel-Diaz** [comment]
You're fine, really. You can keep pushing changes to the branch you are proposing to merge in this PR (monoid_fix), and the new commits will be automatically included in the PR.

**Comment by Kranioceros** [comment]
I've just added a CPP check to make sure it works for older versions of Base. I tested it by passing a -w flag to cabal and it seems to work fine.

**Comment by Daniel-Diaz** [comment]
Great. Thanks!

**Pull request merged**
