### PR TITLE
Improve Creating Blocks section of basics

### PR DESCRIPTION
**Pull request by GetContented**
Improve the English in Creating Blocks section of basics.

### CODE REVIEW

**Comment by Daniel-Diaz** [comment]
Thanks!

**Comment by GetContented** [comment]
I'll have more. I just wanted to see if you were still watching/developing this project. :) Cool.

**Comment by Daniel-Diaz** [comment]
Well... I still am!!

**Comment by Daniel-Diaz** [comment]
Are the new contributions coming soon? I ask it to ponder if it's worth making a release now or better wait for the new improvements.

Thanks!

**Comment by GetContented** [comment]
Oh I'll work on it now.

**Pull request merged**
